[package]
name = "python-lightningcss"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lightningcss"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
browserslist-rs = "0.12.3"
lightningcss = { version = "1.0.0-alpha.44", features = ["browserslist"] }
